### ISSUE TITLE
modify license options

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/collectory-plugin#101]
Add these items to the license type drop down:
CC0
Creative Commons - license detail at record level

The options containing "Share alike" terms should be removed

**Comment by charvolant** [comment]
The code for a manageable licence service is in the master branch from https://github.com/AtlasOfLivingAustralia/collectory-plugin/commit/dd597c266c3bb90d34938ba5b703fb3633eabce4

**Comment by djtfmartin** [comment]
This is now deployed in production
