### ISSUE TITLE
The invisible edit link on the public data resource page is broken

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/collectory-plugin#106]
Previously, clicking on a data resource name on the public data resource page (http://collections.ala.org.au/public/show/drNNNN) next to "Home > Data Resources >" went to the edit page (http://collections.ala.org.au/dataResource/show/drNNNN). Clicking on the data resource name now does not seem to do anything.

A workaround in this case is to manually replace "public" with "dataResource" in the public URL to get to the edit page.

**Comment by nickdos** [comment]
This should be a prominent "Edit" button that only logged-in users with the appropriate role can see - no need for crude hidden links. Ely asked about this as collections people have been asking her, so setting as high priority to fix.
