### ISSUE TITLE
Create new resource page redirects to /admin/index

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/collectory-plugin#107]
Attempting to visit ``collections.ala.org.au/dataResource/create`` gives the browser an HTTP 302 redirect to ``collections.ala.org.au/admin/index`` with no error message. That request then responds with HTTP 302 to redirect to ``collections.ala.org.au/manage/index``, which then responds with HTTP 302 to redirect to ``collections.ala.org.au/admin``.

This seems to mean that no new data resources can be created until this bug is fixed.

**Comment by djtfmartin** [comment]
this is now fixed.

**Comment by ansell** [comment]
Thanks, the create new resource page works now.
