### ISSUE TITLE
Data resources are getting a 'gbif_doi' value that breaks the links on public pages

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/collectory-plugin#146]
See https://github.com/AtlasOfLivingAustralia/collectory-plugin/issues/145.

The process that updates the `gbif_doi` value in the `data_resource` table used to include a prefix of `doi:` but recent data resource entries now contain just the DOI "path". 

E.g.  was: `doi:10.15468/dchsnk` but recently has become `10.15468/dchsnk`.

I suspect the web service that provides the DOI used to pass in `doi:XXXXX/YYYY` but now only provides `XXXXX/YYYY`.

**Comment by timrobertson100** [comment]
Thanks. 
We'll revert that change but it I gather comes from upstream - something relating to the new DataCite API I believe.

Can you please code to accommodate both including and excluding the `doi:`  and then in a future release we'll strip it to follow the [guidelines](https://www.crossref.org/display-guidelines/#display-crossref-doi-as-a-full-link)?

**Comment by nickdos** [comment]
@timrobertson100 thinks the API has changed following the recommendation that `doi:` prefix [no longer be used](https://www.crossref.org/display-guidelines/). I've fixed code to handle both forms of the `gbifDoi` value.

![image](https://user-images.githubusercontent.com/532845/59660746-b36bb300-91ec-11e9-89d9-b2314885659b.png)

**Comment by MattBlissett** [comment]
I think we've provided an unformatted DOI way for around 18 months, so if we revert the change we're likely to cause problems for anyone that's integrated using that API since.

**Comment by timrobertson100** [comment]
Following discussion / investigation at GBIF we are reasonably confident that this change went out 18 months ago and to revert now could break several other systems which makes us hesitate.

Could it be that this has only effected those datasets created within that time and previous ones cached the version with the scheme on the prefix? 

Do you think it is reasonable to encourage the ALA install community to apply the fix you provide here please @nickdos  ?

**Comment by nickdos** [comment]
@timrobertson100 - yes, that sounds reasonable to me. Even if LA groups are not up to date with our latest version, they should be able to patch their code based on my PR for the branch I've created for this issue.

**Comment by timrobertson100** [comment]
Thanks Nick. Please let us know if you hear it is a bigger issue.

**Comment by nickdos** [comment]
Any LA maintainer wanting a patch file to apply to their code base (that may be behind the ALA in version number), use this URL: https://patch-diff.githubusercontent.com/raw/AtlasOfLivingAustralia/collectory-plugin/pull/147.patch

**Comment by nickdos** [comment]
Deployed to https://collections-test.ala.org.au
