### ISSUE TITLE
Collectory URLs only recognise http not https

### ISSUE THREAD

**Issue by peggynewman** [AtlasOfLivingAustralia/collectory-plugin#163]
the collectory seems to only recognise "(http:" (IE: you need the opening bracket and it won't recognise https) as a trigger to display any text as a clickable URL... given that we now only use https URLs, we might want to make sure this is updated if any work is being done... (edited)

**Comment by patkyn** [comment]
https://upsource.ala.org.au/collectory/review/CLLCT-CR-1
