### ISSUE TITLE
Migrate to Ubuntu 20

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/collectory-plugin#173]
Need to get off 16 by April - so idea is to create new test server with version 18 and thoroughly test it.

Do this with #172, https://github.com/AtlasOfLivingAustralia/ala-infrastructure/issues/810 (ala-bootstrap3 update)

**Comment by Rita-C** [comment]
Updated mysql driver
Updated ala-bootstrap3

**Comment by Rita-C** [comment]
Updated app deployed to the new test server.
Waiting for new prod server.
