### ISSUE TITLE
Modify EML generation to include full rights information

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/collectory-plugin#31]
intellectualRights field in the EML needs to include information from:

Rights - if populated
License type - if populated, also needs the license version
License version - include with license type
Attribution - add text: "Attribute as " and attribution

if both rights and license fields are populated then include both.

**Comment by charvolant** [comment]
Using section form to provide information on rights, citation, license and attributions. Example output:

    <intellectualRights>
      <section>
        <title>Rights</title>
        <para>Copyright CSIRO 2015</para>
      </section>
      <section>
        <title>Citation</title>
        <para>Some random person 2015</para>
      </section>
      <section>
        <title>License</title>
        <para>Creative Commons Attribution 3.0</para>
      </section>
    </intellectualRights>

Attributions, if any are ulinks to the collection/institution records.

**Comment by charvolant** [comment]
Pull request https://github.com/AtlasOfLivingAustralia/collectory-plugin/pull/32
