### ISSUE TITLE
Download statistics not showing

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/collectory-plugin#33]
E.g. http://collections.ala.org.au/public/show/co13

There used to be a table with the download stats. There is now only a "download usage stats" button, which produces a CSV file.

**Comment by charvolant** [comment]
Caused by a typo that was still being processed.
Submitted pull request https://github.com/AtlasOfLivingAustralia/collectory-plugin/pull/34/files

**Comment by djtfmartin** [comment]
this is fixed
