### ISSUE TITLE
RIF-CS feed broken - schedule static version?

### ISSUE THREAD

**Issue by nickdos** [AtlasOfLivingAustralia/collectory-plugin#57]
Existing feed reported to be broken:

> From: Martin, Julia (IM&T, Yarralumla) 
> Sent: Monday, 17 August 2015 2:27 PM
> To: Nicholls, Miles (NRCA, Black Mountain) Miles.Nicholls@csiro.au
> Subject: Harvest from ALA
> 
> Hello Miles
> I reviewed the ALA harvest today and noticed it hadn’t run for a significant period.  The harvest point provided is as below.  Could you please let me know if this is still correct?
> Thanks
> Julia
> 
> http://collections.ala.org.au/rif-cs.xml
> 
> Julia Martin

The actual feed appears to be:

http://collections.ala.org.au/ws/rif-cs.xml

but this is quite slow and resource intensive to generate. So Miles has suggested we pre-generate this file via scheduled task to the (non-existing) URL http://collections.ala.org.au/rif-cs.xml 

Check code to see if such as schedule exists and is simply broken.

**Comment by M-Nicholls** [comment]
seems to be working now at this address http://collections.ala.org.au/ws/rif-cs.xml. Several data resource titles were causing problems - encoding of dashes and quotes mostly - and making the process crash.

Will re open if ANDS can't access the URL

**Comment by M-Nicholls** [comment]
Re-open - the spatial type element for each resource needs a coverage wrapper:

e.g. 
<coverage>
  <spatial type="iso19139dcmiBox">northlimit=-20.4; southlimit=-21; westlimit=115.2; eastLimit=115.6; projection=WGS84
  </spatial> 
</coverage>

**Comment by danstoner** [comment]
What is the current status of this issue?  What is "best" link to use? 

This one takes forever and succeeds occasionally:
http://collections.ala.org.au/ws/rif-cs.xml

This one leads to a 404:
http://collections.ala.org.au/rif-cs.xml


Also... xmllint (a command line XML tool) reports the following errors on the output of the first link http://collections.ala.org.au/ws/rif-cs.xml

```
$ xmllint rif-cs.xml
rif-cs.xml:3258: parser error : Entity 'rsquo' not defined
                    <namePart type="full">Australian Museum Mel Ward&rsquo;s Cru
                                                                           ^
rif-cs.xml:3388: parser error : Entity 'rsquo' not defined
                    <namePart type="full">Australian Museum Mel Ward&rsquo;s Cru
                                                                           ^
rif-cs.xml:3476: parser error : Entity 'rsquo' not defined
                    <namePart type="full">Australian Museum Mel Ward&rsquo;s Cru
                                                                           ^
rif-cs.xml:3663: parser error : Entity 'rsquo' not defined
                    <namePart type="full">Australian Museum Mel Ward&rsquo;s Cru
                                                                           ^
rif-cs.xml:3707: parser error : Entity 'rsquo' not defined
                    <namePart type="full">Australian Museum Mel Ward&rsquo;s Cru
                                                                           ^
rif-cs.xml:3970: parser error : Entity 'ndash' not defined
          <namePart type="full">Australian Museum Bivalve Expedition - 9 &ndash;
                                                                               ^
rif-cs.xml:7829: parser error : Entity 'ldquo' not defined
                    <namePart type="full">Gryllidae: &ldquo;True Crickets&rdquo;
                                                            ^
rif-cs.xml:7829: parser error : Entity 'rdquo' not defined
                    <namePart type="full">Gryllidae: &ldquo;True Crickets&rdquo;
                                                                               ^
rif-cs.xml:10708: parser error : Entity 'ndash' not defined
        <namePart type="full">Travel around South Africa with John Acocks&ndash;
                                                                               ^
rif-cs.xml:24604: parser error : Entity 'ndash' not defined
             <namePart type="full">Allan McEvey&#39;s Journal: Nullarbor &ndash;
                                                                               ^
rif-cs.xml:28114: parser error : Entity 'ndash' not defined
        <namePart type="full">Travel around South Africa with John Acocks&ndash;
```

**Comment by nickdos** [comment]
I think the public URL should be:

http://collections.ala.org.au/rif-cs.xml

which should have a `urlMappings` entry pointing it to the `/ws/rif-cs.xml` end-point.

**Comment by nickdos** [comment]
Committed fixes:
 * URL is http://collections.ala.org.au/rif-cs.xml
 * named entities not appearing
 * invalid bytes for UTF-8 fixed
 * `coverage` element added to `spatial` tags
 * service method added with eh-cache caching of method values

**Comment by danstoner** [comment]
Maybe the scheduled job hasn't run yet. The URL http://collections.ala.org.au/rif-cs.xml still leads to a 404.

![2015-11-19-081409_1327x987_scrot](https://cloud.githubusercontent.com/assets/2325459/11271714/ee5f6fa0-8e95-11e5-8179-21161047f6c7.png)

**Comment by nickdos** [comment]
Yep, sorry not deployed yet (only committed) - was trying to do this today but ran into issues running our ansible script. Will update when available.

**Comment by nickdos** [comment]
OK new version is running on prod. 

 http://collections.ala.org.au/rif-cs.xml is working but it takes a while to run (spatial bounds lookups are the slow step).

**Comment by nickdos** [comment]
Data change has broken the feed again for DR105:

```
<registryObject group="Atlas of Living Australia">
            <key>ala.org.au/dr105</key>
            <!DOCTYPE html>
<html>
<head>
    <title>Error</title>
    <meta name="layout" content="ala"/>
    
</head>
<body>
<h1>
    An error has occurred
</h1>

    <ul class="errors">
        <li>Error: unknown</li>
    </ul>


</body>
</html>
```

**Comment by nickdos** [comment]
Was fixed shortly after last comment.
