### ISSUE TITLE
Permissions to allow users to edit collectory pages not working

### ISSUE THREAD

**Issue by M-Nicholls** [AtlasOfLivingAustralia/collectory-plugin#59]
From previous hip chat discussion in the Auth room:

partially working with role_editor, they can get to the collection admin page but if they click the edit button on a section it returns an error: unknown. it should be possible that by setting someone as the editor when adding them to the contacts for the collection they are granted access to edit that collection

**Comment by nickdos** [comment]
Managed to replicate issue and fixed - error was due to missing import.
