### ISSUE TITLE
Public pages for data resources are broken

### ISSUE THREAD

**Issue by djtfmartin** [AtlasOfLivingAustralia/collectory-plugin#8]
![screen shot 2015-01-16 at 11 26 28 am](https://cloud.githubusercontent.com/assets/444897/5769645/92e630ec-9d72-11e4-823b-e178e1e2c6aa.png)

**Comment by linaizhong** [comment]
This is fixed in generic-collectory. Please also set the following attribute in *-config.properties:
security.cas.bypass=true

**Comment by linaizhong** [comment]
Fixed.
